#!/bin/bash

# Função para solicitar as informações de acesso ao usuário
get_credentials() {
  read -p "Digite o IP do iDRAC: " idrac_ip
  read -s -p "Digite o usuário do iDRAC: " username
  read -s -p "Digite a senha do iDRAC: " password
  echo
}

# Função para salvar a licença
save_license() {
  racadm -r $idrac_ip -u $username -p $password getconfig -c cfgLicense > licenca_idrac.txt
  if [ $? -eq 0 ]; then
    echo "Licença salva com sucesso em licenca_idrac.txt"
  else
    echo "Erro ao salvar a licença"
  fi
}

# Solicitar as informações de acesso
get_credentials

# Salvar a licença
save_license
